ktor {
    deployment {
        port = 8080
        port = ${?SERVER_PORT}
    }
}

database {
    url = "jdbc:postgresql://localhost:5433/guidebook_db"
    url = ${?DATABASE_URL}
    user = "app"
    user = ${?DATABASE_USER}
    password = "app_password"
    password = ${?DATABASE_PASSWORD}
}

jwt {
    secret = "change-me-to-long-random-string-at-least-32-chars"
    secret = ${?JWT_SECRET}
    issuer = "guidebook"
    issuer = ${?JWT_ISSUER}
    audience = "guidebook-clients"
    audience = ${?JWT_AUDIENCE}
    realm = "Guidebook API"
    realm = ${?JWT_REALM}
}

storage {
    path = "./storage"
    path = ${?STORAGE_PATH}
}

server {
    baseUrl = "http://localhost:8080"
    baseUrl = ${?SERVER_BASE_URL}
}
